scanner/application/urls.py
from django.contrib import admin
from django.urls import path,include
from application import views
app_name="application"

urlpatterns = [
    path('',views.base,name='base'),
    path('image/',views.image_upload,name='imageupload'),
    path('pdf/',views.pdf_upload,name='pdfupload'),
    path('text/',views.text_upload,name='textupload'),
    path('imageextract/',views.imageextract,name='imageextract'),
    path('pdfextract/',views.pdf_extract,name='pdfextract'),
    path('getdata/',views.getdata,name='getdata'),
    path('translate/',views.translation,name='translate'),
    path('gettext/',views.get_text,name='gettext'),
    path('texttranslate',views.text_translation,name='texttranslate')

]

scanner/scanner/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('application.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

scanner/application/models.py
from django.db import models

class ImageUpload(models.Model):
    files=models.ImageField(upload_to='images/')
    uploaded_at=models.DateTimeField(auto_now_add=True)



class PdfUpload(models.Model):
    files=models.FileField(upload_to='pdf')
    uploaded_at=models.DateTimeField(auto_now_add=True)


class TextUpload(models.Model):
    text=models.TextField()
    uploaded_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

class ExtractedData(models.Model):
    text=models.TextField()
    uploaded_at=models.DateTimeField(auto_now_add=True)

scanner/application/forms.py
from django import forms
from application.models import ImageUpload,PdfUpload,TextUpload

class ImageUploadForm(forms.ModelForm):
    class Meta:
        model=ImageUpload
        fields="__all__"

class PdfUploadForm(forms.ModelForm):
    class Meta:
        model=PdfUpload
        fields="__all__"

class TextUploadForm(forms.ModelForm):
    class Meta:
        model=TextUpload
        fields="__all__"

scanner/application/views.py
from django.shortcuts import render,redirect
from application.forms import ImageUploadForm,PdfUploadForm,TextUploadForm
from application.models import ImageUpload,ExtractedData,TextUpload,PdfUpload
from django.http import JsonResponse
from pytesseract import pytesseract
from PIL import Image
from django.http import HttpResponse
from application.serializers import ExtractedSerializer
import pdfplumber
from googletrans import LANGUAGES
from .translator import translate_text
import os

def base(request):
    return render(request,'home.html')

def image_upload(request):
    if(request.method=="POST"):
        i=request.FILES.get('i')
        img=ImageUpload.objects.create(files=i)
        img.save()
        return imageextract(request)

    return render(request,'imageupload.html')

def text_upload(request):
    if(request.method=="POST"):
        t=request.POST.get('t')
        text=TextUpload.objects.create(text=t)
        text.save()
        return get_text(request)
    return render(request,'textupload.html')

def pdf_upload(request):
    if request.method == "POST":
        p = request.FILES.get('p')
        pdf = PdfUpload.objects.create(files=p)
        pdf.save()
        return pdf_extract(request)

    return render(request, 'pdfupload.html')


def imageextract(request):
    if request.method == 'POST':
        # Get the uploaded image
        img = ImageUpload.objects.latest('uploaded_at') # You might want to filter or select the image in a specific way

        if img:
            image = Image.open(img.files.path)
            pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'

            # Perform OCR to extract text from the image
            extracted_text = pytesseract.image_to_string(image)

            # Create a new ExtractedData object and save the extracted text
            data = ExtractedData.objects.create(text=extracted_text)
            data.save()

            # Return the extracted text as JSON
            return render(request, 'extracted.html', {'extracted_text': extracted_text})
        else:
            return render(request, 'errorpage.html', {'error': 'No image uploaded'})

    return render(request, 'imgextract.html')

def pdf_extract(request):
    if request.method == "POST":
        try:
            pdf = PdfUpload.objects.latest("uploaded_at")
            if pdf and pdf.files:
                # Check if the 'files' attribute is not None
                with pdfplumber.open(pdf.files.path) as pdf_doc:
                    extracted_text = ""
                    for page in pdf_doc.pages:
                        extracted_text += page.extract_text()
                        data = ExtractedData.objects.create(text=extracted_text)
                        data.save()


                # You can now use 'extracted_text' in your template or perform further processing
                return render(request, 'extracted.html', {'extracted_text': extracted_text})
            else:
                # Handle the case where 'pdf' or 'pdf.files' is None
                return render(request, 'errorpage.html', {'error_message': 'No PDF file found.'})
        except PdfUpload.DoesNotExist:
            # Handle the case where no PdfUpload objects are found
            return render(request, 'errorpage.html', {'error_message': 'No PDF uploaded yet.'})

    return render(request, 'pdfextract.html')

def getdata(request):
    data=ExtractedData.objects.latest('uploaded_at')
    data_str=data.text
    print(data_str)
    print(type(data_str))
    return render(request, 'home.html')

def translation(request):
    if request.method == "POST":
        lang_code = request.POST.get('lang_code')

        data = ExtractedData.objects.latest('uploaded_at')
        data_str = data.text

        translated_text = translate_text(data_str, "en", lang_code)
        return render(request, 'translated.html', {'translated_text': translated_text})
    return render(request, 'translate.html')

# def text_extract(request):
#     if request.method=="POST":
#         data=TextUpload.objects.latest('uploaded_at')
#         if data:
#             obj=ExtractedData()
#             obj.text=data.text
#             obj.save()
#         else:
#             pass
#         return translation(request)

def get_text(request):
    text=TextUpload.objects.latest('uploaded_at')
    return render(request,'text.html',{'text':text})

def text_translation(request):
    if request.method == "POST":
        lang_code = request.POST.get('lang_code')

        data = TextUpload.objects.latest('uploaded_at')
        data_str = data.text

        translated_text = translate_text(data_str, "en", lang_code)
        return render(request, 'translated.html', {'translated_text': translated_text})
    return render(request, 'translate.html')

scanner/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" rel="stylesheet">

</head>

<body>


</body>
</html>
{% block content %}
{% endblock %}

scanner/templates/errorpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{error_message}}
</body>
</html>

scanner/templates/extracted.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST" style="color:white;">
   {% csrf_token %}
{{extracted_text}}
   &nbsp; &nbsp; &nbsp;
   <center>
<a class="btn btn-warning" href="{% url 'application:translate' %}">GoToTranslate</a>
   </center>
</form>
{% endblock %}

scanner/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'style1.css' %}">
<div class="container body1">
    <div class="row">
        <div class="col-sm-3 x1" style="">
            <a href="{% url 'application:imageupload' %}"><i class="fa-solid fa-image fa-7x" style="color: #ffffff;"></i></a>
            <p class="p1">Image</p>
        </div>
        <div class="col-sm-3 x2" style="">
            <a href="{% url 'application:textupload' %}"><i class="fa-solid fa-file-lines fa-7x" style="color: #ffffff;"></i></a>
            <p class="p1">Text</p>
        </div>
        <div class="col-sm-3 x3" style="">
            <a href="{% url 'application:pdfupload' %}"><i class="fa-solid fa-file-pdf fa-7x" style="color: #ffffff;"></i></a>
            <p class="p1">PDF</p>
        </div>
        <div class="col-sm-3 x4" style="">
            <a><i class="fa-solid fa-camera fa-7x" style="color: #ffffff;"></i></a>
            <p class="p1">CamScan</p>
        </div>
    </div>

</div>
{% endblock %}

scanner/templates/imageupload.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
  <div class="mb-3" style="width:75%;padding:50px;position:relative;">
    <label class="form-label" style="color:white">Image</label>
    <input type="file" class="form-control" name="i" placeholder="Upload Image">
  </div>

  <input type="submit" class="btn btn-warning" style="position:absolute;left:100px;top:130px;">
</form>
{% endblock %}

scanner/templates/imgextract.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<form>
  <center>
    <input type="submit" value="Extract" class="btn btn-warning">
  </center>
</form>
{% endblock %}

scanner/templates/pdfextract.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST" style="color:white;" enctype="multipart/form-data">
   {% csrf_token %}

   <center>
<input type="submit"  class="btn btn-warning">
   </center>
</form>
{% endblock %}

scanner/templates/pdfupload.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
  <div class="mb-3" style="width:75%;padding:50px;position:relative;">
    <label class="form-label" style="color:white">PDF</label>
    <input type="file" class="form-control" name="p" placeholder="Upload PDF">
  </div>

  <input type="submit" class="btn btn-warning" style="position:absolute;left:100px;top:130px;">
</form>
{% endblock %}

scanner/templates/text.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST" style="color:white;">
   {% csrf_token %}
{{text}}
   &nbsp; &nbsp; &nbsp;
   <center>
<a class="btn btn-warning" href="{% url 'application:texttranslate' %}">GoToTranslate</a>
   </center>
</form>
{% endblock %}

scanner/templates/textupload.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
  <div class="mb-3" style="width:75%;padding:50px;position:relative;">
    <label class="form-label" style="color:white">TEXT</label>
    <input type="text" class="form-control" name="t" placeholder="Upload Text">
  </div>

  <input type="submit" class="btn btn-warning" style="position:absolute;left:100px;top:130px;">
</form>
{% endblock %}

scanner/templates/translate.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'style4.css' %}">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
  <div class="mb-3" style="width:40%;padding:50px;position:relative;">
    <label class="form-label" style="color:white">(e.g., 'fr' for French)</label>
    <input type="text" class="form-control" name="lang_code" placeholder="en_To_Prefferedlanguage">
  </div>
  <input type="submit" class="btn btn-warning" style="position:absolute;left:100px;top:130px;">
</form>
  <div style="position:absolute;right:80px;top:30px;bottom:30px;color:white;padding:10px;">
<h5>Supported Languages:</h5>
    af: afrikaans<br>
sq: albanian<br>
am: amharic<br>
ar: arabic<br>
hy: armenian<br>
az: azerbaijani<br>
<div id="languageList">
eu: basque<br>
be: belarusian<br>
bn: bengali<br>
bs: bosnian<br>
bg: bulgarian<br>
ca: catalan<br>
ceb: cebuano<br>
ny: chichewa<br>
zh-cn: chinese (simplified)<br>
zh-tw: chinese (traditional)<br>
co: corsican<br>
hr: croatian<br>
cs: czech<br>
da: danish<br>
nl: dutch<br>
en: english<br>
eo: esperanto<br>
et: estonian<br>
tl: filipino<br>
fi: finnish<br>
fr: french<br>
fy: frisian<br>
gl: galician<br>
ka: georgian<br>
de: german<br>
el: greek<br>
gu: gujarati<br>
ht: haitian creole<br>
ha: hausa<br>
haw: hawaiian<br>
iw: hebrew<br>

he: hebrew<br>
hi: hindi<br>
hmn: hmong<br>
hu: hungarian<br>
is: icelandic<br>
ig: igbo<br>
id: indonesian<br>
ga: irish<br>
it: italian<br>
ja: japanese<br>
jw: javanese<br>
kn: kannada<br>
kk: kazakh<br>
km: khmer<br>
ko: korean<br>
ku: kurdish (kurmanji)<br>
ky: kyrgyz<br>
lo: lao<br>
la: latin<br>
lv: latvian<br>
lt: lithuanian<br>
lb: luxembourgish<br>
mk: macedonian<br>
mg: malagasy<br>
ms: malay<br>
ml: malayalam<br>
mt: maltese<br>
mi: maori<br>
mr: marathi<br>
mn: mongolian<br>
my: myanmar (burmese)<br>
ne: nepali<br>
no: norwegian<br>
or: odia<br>
ps: pashto<br>
fa: persian<br>
pl: polish<br>
pt: portuguese<br>
pa: punjabi<br>
ro: romanian<br>
ru: russian<br>
sm: samoan<br>
gd: scots gaelic<br>
sr: serbian<br>
st: sesotho<br>
sn: shona<br>
sd: sindhi<br>
si: sinhala<br>
sk: slovak<br>
sl: slovenian<br>
so: somali<br>
es: spanish<br>
su: sundanese<br>
sw: swahili<br>
sv: swedish<br>
tg: tajik<br>
ta: tamil<br>
te: telugu<br>
th: thai<br>
tr: turkish<br>
uk: ukrainian<br>
ur: urdu<br>
ug: uyghur<br>
uz: uzbek<br>
vi: vietnamese<br>
cy: welsh<br>
xh: xhosa<br>
yi: yiddish<br>
yo: yoruba<br>
zu: zulu<br>
  </div>
 </div>
<div style="position:absolute;right:350px;">
<a class="btn btn-danger" id="toggleButton">Read More</a>
 </div>
    <script>
        const languageList = document.getElementById('languageList');
        const toggleButton = document.getElementById('toggleButton');

        let isExpanded = false;

        toggleButton.addEventListener('click', () => {
            isExpanded = !isExpanded;

            if (isExpanded) {
                languageList.classList.remove('hidden');
                toggleButton.textContent = 'Read Less';
            } else {
                languageList.classList.add('hidden');
                toggleButton.textContent = 'Read More';
            }
        });
    </script>

{% endblock %}

scanner/templates/translated.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div style="color:white;">
{{translated_text}}
</div>
{% endblock %}